[package]
name = "learning-opengl"
version = "0.1.0"
authors = ["Yuichiro MUKAI <y.iky917@gmail.com>"]

[dependencies]
gl = "0.9.0"
glfw = "0.20.0"

[[bin]]
name = "1_2_1"
path = "src/1_getting_started/2_1_hello_triangle.rs"